module Dark::ELF::Callbacks
  # Callbacks - Implements the output API functions for object file execution
  #
  # The callbacks act as a bridge between the Crystal agent and the C object file code,
  # allowing object files to output text, allocate memory, and perform other operations
  # through the standard callback API.
  extend self

  #
  # ======================================================================
  # CONSTANTS AND TYPES
  # ======================================================================

  # Registry of callback function names to memory addresses
  @@callbacks = {} of String => UInt64

  # Buffer to capture callback output during BOF execution
  @@output_buffer = IO::Memory.new
  @@error_buffer  = IO::Memory.new

  # Thread-safe access to output buffers
  @@buffer_mutex = Mutex.new

  #
  # ======================================================================
  # OUTPUT MANAGEMENT
  # ======================================================================
  #
  # Get the accumulated output and clear the buffer
  #
  # This method is called after BOF execution to retrieve all output
  # generated by the BOF through callback API calls.
  #
  # @return [String] All captured output since the buffer was last cleared
  def get_and_clear_output : String
    @@buffer_mutex.synchronize do
      output = @@output_buffer.to_s
      @@output_buffer.clear
      output
    end
  end

  # ======================================================================
  # CALLBACK REGISTRY MANAGEMENT
  # ======================================================================
  #

  # Register a callback function by name and memory address
  #
  # @param name [String] The name of the callback function (e.g., "BeaconPrintf")
  # @param address [UInt64] The memory address of the callback function
  def register(name : String, address : UInt64)
    @@callbacks[name] = address
    log_debug "Registered callback '#{name}' at 0x#{address.to_s(16)}"
  end

  # Look up a callback function's address by name
  #
  # @param name [String] The name of the callback function to look up
  # @return [UInt64?] The memory address of the callback, or nil if not found
  def lookup(name : String) : UInt64?
    @@callbacks[name]?
  end

  # Log a list of all registered callbacks
  def list
    if @@callbacks.empty?
      log_debug "No callbacks registered"
    else
      log_debug "Registered callbacks:"
      @@callbacks.each do |name, addr|
        log_debug "  #{name}: 0x#{addr.to_s(16)}"
      end
    end
  end

  # Clear all registered callbacks
  def clear
    @@callbacks.clear
    log_debug "All callbacks cleared"
  end

  # Get the number of registered callbacks
  #
  # @return [Int32] The number of callbacks in the registry
  def count
    @@callbacks.size
  end

  # Check if a callback is registered by name
  #
  # @param name [String] The name of the callback to check
  # @return [Bool] True if the callback is registered, false otherwise
  def has_callback?(name : String) : Bool
    @@callbacks.has_key?(name)
  end

  #
  # ======================================================================
  # STRING UTILITIES
  # ======================================================================
  #

  # Helper method to calculate safe length to read
  private def calculate_safe_length(data : Pointer(UInt8), len : Int32) : Int32
    if len > 0 && len <= 10_485_760
      return len
    end

    # If no valid length provided, find string length (up to max)
    max_check = 10240
    i = 0
    while i < max_check
      begin
        break if data[i] == 0
        i += 1
      rescue
        break
      end
    end
    return i
  end

  # Helper method to read bytes safely
  private def read_bytes_safely(data : Pointer(UInt8), length : Int32) : String
    bytes = [] of UInt8
    length.times do |i|
      begin
        bytes << data[i]
      rescue
        break
      end
    end

    # Convert to string or printable representation
    begin
      String.new(bytes.to_unsafe, bytes.size)
    rescue
      bytes.map { |b| (32..126).includes?(b) ? b.chr : '�' }.join
    end
  end

  #
  # ======================================================================
  # FORMAT STRING PROCESSING
  # ======================================================================
  #
  # Process format string with arguments for BeaconPrintf
  def process_format_string(fmt, args) : String
    result = fmt.dup

    # Iterate the arguments to keep the match with the appropriate replacement.
    # If we have %s and %d in the same string, you want to ensure you have the
    # correct arg0 or arg1 for the match.
    args.each_with_index do |arg, index|
      if match = result.match(/%[sdpx]/)
        specifier = match[0]

        {% if flag?(:debugmem) %}
          puts "Found: #{specifier} - ARG: #{arg} - Index: #{index}"
        {% end %}

        replacement = case specifier
        when "%s"
          if arg.null?
            "<NULL POINTER>"
          else
            begin
              str = String.new(arg)
              {% if flag?(:debugmem) %}
                log_error "String value: '#{str}'"
              {% end %}
              str
            rescue ex
              {% if flag?(:debugmem) %}
                log_error "Error reading string: #{ex.message}"
              {% end %}
              "<STRING ERROR>"
            end
          end
        when "%d"
          arg.address.to_s
        when "%p"
          "0x#{arg.address.to_s(16)}"  # Format as hex pointer
        when "%x"
          "0x#{arg.address.to_s(16)}"  # Raw hex value
        end

        {% if flag?(:debugmem) %}
          log_error "ARG: #{arg} - Replacement: #{replacement}"
        {% end %}

        # Remove the specifier
        result = result.sub(specifier, replacement)
      end
    end

    return result
  end

  #
  # ======================================================================
  # PRINTF CALLBACK
  # ======================================================================
  #
  # BeaconPrintf supports 5 arguments currently.  Crystal callbacks do not have
  # support for variadic arguments, so we hard code them here
  def register_printf
    callback = ->(fmt : UInt8*, arg0 : UInt8*, arg1 : UInt8*, arg2 : UInt8*, arg3 : UInt8*, arg4: UInt8*, arg5: UInt8*, arg6: UInt8*, arg7: UInt8*, arg8: UInt8*, arg9: UInt8*) {

      # Create an array of arguments
      # Iterate until a null pointer is found
      args = [] of UInt8*
      all_args = [arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9]
      all_args.each_with_index do |arg, index|
        break if arg.address == 0xcc
        {% if flag?(:debugmem) %}
          log_error arg
        {% end %}
        args << arg
      end

      # Debug information
      {% if flag?(:debugmem) %}
        dump_memory_analysis(fmt)
        log_error "STR: #{fmt}"
        log_error "STR New: #{String.new(fmt)}"
      {% end %}

      str    = String.new(fmt)
      output = process_format_string(str, args)
      @@buffer_mutex.synchronize do
        @@output_buffer << "#{output}\n"
      end
    }
    register("BeaconPrintf", callback.pointer.address)
  end


  #
  # ======================================================================
  # DEBUG MEMORY ANALYSIS
  # ======================================================================
  {% if flag?(:debugmem) %}
  # Simplified memory analysis for debugging
  private def dump_memory_analysis(fmt : UInt8*)
    puts "---------- FORMAT STRING MEMORY ----------"
    puts "Pointer: 0x#{fmt.address.to_s(16)}"

    # Display the actual string that matters
    begin
      str = String.new(fmt)
      puts "String at offset: '#{str}'"
    rescue ex
      puts "Error reading string: #{ex.message}"
    end
    puts "----------------------------------------"
  end
  {% end %}

  #
  # ======================================================================
  # OUTPUT CALLBACK
  # ======================================================================
  #

  def register_output
    callback = ->(data : Pointer(UInt8), len : Int32) {
      if data.null?
        @@buffer_mutex.synchronize do
          @@output_buffer << "[ERROR] Null data pointer" << "\n"
        end
        log_debug "[ERROR] Null data pointer"
        return
      end

      # Determine safe length to read
      safe_len = calculate_safe_length(data, len)

      if safe_len <= 0
        @@buffer_mutex.synchronize do
          @@output_buffer << "\n"
        end
        return
      end

      # Read bytes and convert to string
      output_str = read_bytes_safely(data, safe_len)
      @@buffer_mutex.synchronize do
        @@output_buffer << output_str << "\n"
      end
    }
    register("BeaconOutput", callback.pointer.address)
  end

  #
  # ======================================================================
  # INITIALIZATION
  # ======================================================================
  #

  def register_defaults
    # Clear the output buffer before registering callbacks
    @@buffer_mutex.synchronize do
      @@output_buffer.clear
    end
    register_printf
    register_output
  end
end